# Generated by Django 3.2.5 on 2021-07-13 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20, verbose_name='Клиент')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PurchasedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30, verbose_name='Предмет')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('customer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customerlog', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
