# Generated by Django 3.2.5 on 2021-07-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='customer_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pur_item', to='mainapp.customerlog', verbose_name='Клиент'),
        ),
    ]
