# Generated by Django 3.2.5 on 2021-07-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_purchaseditems_customer_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlog',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
