# Generated by Django 3.2.5 on 2021-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_customerlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditems',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
